async function railMetric(a,b){const key=metricKey(a,b,'rail'),cached=getCached(key);if(cached)return cached;const c=amapCfg();if(!c.webKey)return{km:null,time:'待12306锁定具体车次',source:'铁路班次未锁定',kind:'pending'};bumpUsage();const s=coord(a),e=coord(b);if(!s||!e)return{km:null,time:'待确认',source:'坐标缺失',kind:'pending'};const url=`https://restapi.amap.com/v3/direction/transit/integrated?key=${encodeURIComponent(c.webKey)}&origin=${s.join(',')}&destination=${e.join(',')}&city=青岛&cityd=威海&extensions=all&strategy=0`;try{const d=await jsonp(url),seg=d.route?.transits?.[0]?.segments||[];let dm=0,sec=0;seg.forEach(x=>{if(x.railway&&x.railway.id){dm+=Number(x.railway.distance||0);sec+=Number(x.railway.time||0)}});if(!dm){dm=Number(d.route?.distance||0)}const v={km:dm?dm/1000:null,time:sec?`${Math.round(sec/60)} 分钟`:'以12306具体车次为准',source:'高德跨城公交/铁路结果；最终以12306为准',kind:'live'};setCached(key,v);return v}catch{return{km:null,time:'以12306具体车次为准',source:'铁路查询失败',kind:'pending'}}}
function planButtons(){return Object.keys(PLAN).map(k=>`<button type="button" class="plan-pick ${k===selected?'active':''}" data-plan-pick="${k}">${k}${k==='A'?' 主推':''}</button>`).join('')}
function wirePickers(){document.getElementById('overviewPlanPicker').innerHTML=planButtons();document.getElementById('journeyPlanPicker').innerHTML=planButtons();document.querySelectorAll('[data-plan-pick]').forEach(b=>b.onclick=()=>{selected=b.dataset.planPick;localStorage.setItem('trip:selectedPlan',selected);wirePickers();renderJourney()});document.getElementById('journeyCurrentTitle').textContent=PLAN[selected].name;document.querySelectorAll('#quick tbody tr').forEach(r=>{const k=r.querySelector('td b')?.textContent.trim();if(PLAN[k]){r.style.cursor='pointer';r.style.outline=k===selected?'2px solid #8d75ca':'none';r.onclick=()=>{selected=k;localStorage.setItem('trip:selectedPlan',k);wirePickers();switchView('journey')}}})}
function switchView(v,sub){document.querySelectorAll('.app-view').forEach(x=>x.hidden=x.dataset.view!==v);document.querySelectorAll('[data-view-btn]').forEach(x=>x.classList.toggle('active',x.dataset.viewBtn===v));document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));const b=document.querySelector(`[data-bottom="${v==='overview'?'overview':v==='journey'?'days':sub==='booking'?'booking':'research'}"]`);if(b)b.classList.add('active');history.replaceState(null,'','#'+v);if(v==='journey')renderJourney();if(v==='research'&&sub==='booking')setTimeout(()=>document.getElementById('booking')?.scrollIntoView({behavior:'smooth'}),80);window.scrollTo({top:0,behavior:'smooth'})}
function daySummary(keys){return keys.map((k,i)=>{const d=MAPDATA[k],date=dayDate(d),city=(d.title||'').replace(/^\d+\/\d+\s*/,''),first=(LOCS[d.nodes[0][0]]||[d.nodes[0][0]])[0],last=(LOCS[d.nodes.at(-1)[0]]||[d.nodes.at(-1)[0]])[0];return`<div class="plan-day-card"><div class="daytop"><div class="daytitle">Day ${i+1}｜${city}</div><div class="daydate">${date}</div></div><div class="daycity">${first} → ${last}</div><div class="daybrief">${d.nodes.length} 个关键节点；详细距离、时长与地图看下方。</div></div>`}).join('')}
function edgeLine(a,b,m,i){const f=fixedMetric(a,b,m),initial=f?fmtMetric(f):(m==='rail'?'距离/时长待铁路查询':'配置高德后计算实际路线');return`<div class="flow-mode"><span class="chip">${modeText[m]||m}</span><span>${(LOCS[a]||[a])[0]} → ${(LOCS[b]||[b])[0]}</span><span class="edge-metric ${f?.kind||'pending'}" data-edge="${a}|${b}|${m}">${initial}</span></div>`}
function flowMap(d){const date=dayDate(d),pts=d.nodes.map((n,i)=>({key:n[0],name:(LOCS[n[0]]||[n[0]])[0],city:nodeCity(n[0]),time:n[1],note:n[2],i:i+1})),modes=d.modes||[];let s=`<div class="route-summary"><div class="pill"><b>日期</b><br>${date}</div><div class="pill"><b>关键节点</b><br>${pts.length} 个</div><div class="pill"><b>说明</b><br>陆地距离/时长优先取高德实际路线</div></div><div class="flow-steps">`;pts.forEach((p,i)=>{s+=`<div class="flow-step"><div class="num">${i+1}</div><div class="box"><div class="nm">${p.name}</div><div class="meta">${date}｜${p.city}</div><div class="tm">${p.time}</div><div class="nt">${p.note||''}</div></div></div>`;if(i<pts.length-1)s+=edgeLine(p.key,pts[i+1].key,modes[i]||'taxi',i)});return s+'</div>'}
function longhaulCard(a,b,m){const f=fixedMetric(a,b,m),metric=f?fmtMetric(f):(m==='rail'?'待12306 / 高德 Web Service':'待确认');return`<div class="longhaul-card"><div class="longhaul-icon">${(modeText[m]||m).split(' ')[0]}</div><div><div class="longhaul-title">${(LOCS[a]||[a])[0]} → ${(LOCS[b]||[b])[0]}</div><div class="longhaul-meta">${m==='flight'?'航空段采用大圆直线距离；时长按锁定航班':m==='rail'?'铁路段距离/时长优先用跨城铁路结果，最终以12306具体车次':'长途转场'}</div></div><div class="longhaul-kpi" data-edge="${a}|${b}|${m}">${metric}</div></div>`}
function splitGroups(d){const nodes=d.nodes,modes=d.modes||[],groups=[],haul=[];let cur=[nodes[0]];for(let i=0;i<modes.length;i++){const m=modes[i],next=nodes[i+1];if(m==='flight'||m==='rail'){if(cur.length>1)groups.push(cur);else if(cur.length===1)groups.push(cur);haul.push({a:nodes[i][0],b:next[0],mode:m});cur=[next]}else cur.push(next)}if(cur.length)groups.push(cur);return{groups,haul}}
function numberedMarker(map,p,i){const c=coord(p[0]);if(!c)return;new AMap.Marker({map,position:c,content:`<div class="amap-num">${i+1}</div>`,offset:new AMap.Pixel(-15,-15),title:(LOCS[p[0]]||[p[0]])[0]})}
async function drawGroup(el,nodes){const c=amapCfg();if(!c.jsKey||!c.security){el.innerHTML='<div class="amap-placeholder">配置高德 JS API Key + securityJsCode 后，这里会直接显示内嵌路线地图。<br>未配置时，完整执行流程仍可使用。</div>';return}try{await loadAmap();el.innerHTML='';const pts=nodes.map(n=>coord(n[0])).filter(Boolean),center=pts[0]||[116.4,39.9],map=new AMap.Map(el,{zoom:11,center,viewMode:'2D'});nodes.forEach((n,i)=>numberedMarker(map,n,i));if(pts.length>1)map.setFitView();for(let i=0;i<nodes.length-1;i++){const a=nodes[i][0],b=nodes[i+1][0],dKey=findDayEdgeMode(a,b),mode=dKey||'taxi';if(mode==='ferry'){new AMap.Polyline({map,path:[coord(a),coord(b)],strokeColor:'#2e86ab',strokeWeight:4,strokeStyle:'dashed'});continue}try{await jsRouteMetric(a,b,mode,map)}catch(e){new AMap.Polyline({map,path:[coord(a),coord(b)],strokeColor:'#aaa',strokeWeight:3,strokeStyle:'dashed'})}}map.setFitView()}catch(e){el.innerHTML=`<div class="amap-placeholder">高德地图加载失败：${e.message}</div>`}}
let ACTIVE_DAY=null;
function findDayEdgeMode(a,b){if(!ACTIVE_DAY)return null;const ns=ACTIVE_DAY.nodes;for(let i=0;i<ns.length-1;i++)if(ns[i][0]===a&&ns[i+1][0]===b)return ACTIVE_DAY.modes[i];return null}
function renderDayMap(d,key){const {groups,haul}=splitGroups(d);let gi=0,hi=0,html='<div class="day-map-section"><h4>🗺️ 当天内嵌高德路线图</h4><div class="amap-groups">';for(let i=0;i<groups.length;i++){const g=groups[i];if(g.length){html+=`<div class="amap-panel"><div class="amap-panel-head">${i===0?'本地路线':'到达后本地路线'}｜${g.map(n=>(LOCS[n[0]]||[n[0]])[0]).join(' → ')}</div><div class="amap-canvas" data-map-group="${key}|${i}"><div class="map-loading">等待地图加载</div></div></div>`}if(haul[i])html+=longhaulCard(haul[i].a,haul[i].b,haul[i].mode)}html+='</div><div class="map-legend">地图只放编号节点和真实路线，不再把长标签叠在图上；跨城航空/铁路单独拆卡，避免全国尺度挤压市内地图。</div></div>';return html}
async function hydrateDay(details,d,key){ACTIVE_DAY=d;details.querySelectorAll('[data-edge]').forEach(async el=>{const [a,b,m]=el.dataset.edge.split('|');try{const x=await jsRouteMetric(a,b,m);el.textContent=fmtMetric(x);el.className='edge-metric '+(x.kind||'live')}catch(e){el.textContent='未计算：'+e.message;el.className='edge-metric pending'}});const groups=splitGroups(d).groups;details.querySelectorAll('[data-map-group]').forEach((el,i)=>drawGroup(el,groups[i]))}
